### ISSUE TITLE
ValueError: This converter can only convert a single ConcreteFunction. Converting multiple functions is under development.

### ISSUE THREAD

**Issue by soumyaiitkgp** [tensorflow/tflite-support#427]
Upon converting .pb file to .tflite I get the following error:

> 2021-04-04 23:07:05.398922: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
INFO:tensorflow:Saver not created because there are no variables in the graph to restore
I0404 23:07:14.163655  1356 saver.py:1503] Saver not created because there are no variables in the graph to restore
2021-04-04 23:07:14.182173: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2021-04-04 23:07:15.144923: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: NVIDIA GeForce GTX 1050 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.62
pciBusID: 0000:01:00.0
2021-04-04 23:07:15.145101: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2021-04-04 23:07:15.147434: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2021-04-04 23:07:15.158033: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2021-04-04 23:07:15.162610: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: NVIDIA GeForce GTX 1050 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.62
pciBusID: 0000:01:00.0
2021-04-04 23:07:15.162774: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2021-04-04 23:07:15.162945: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2021-04-04 23:07:19.332432: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-04-04 23:07:19.332565: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0
2021-04-04 23:07:19.332680: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N
2021-04-04 23:07:19.336138: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2996 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce GTX 1050 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "C:\Users\test\anaconda3\envs\tf2\Scripts\tflite_convert-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\test\anaconda3\envs\tf2\lib\site-packages\tensorflow_core\lite\python\tflite_convert.py", line 515, in main
    app.run(main=run_main, argv=sys.argv[:1])
  File "C:\Users\test\anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\test\anaconda3\envs\tf2\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "C:\Users\test\anaconda3\envs\tf2\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "C:\Users\test\anaconda3\envs\tf2\lib\site-packages\tensorflow_core\lite\python\tflite_convert.py", line 502, in run_main
    _convert_tf2_model(tflite_flags)
  File "C:\Users\test\anaconda3\envs\tf2\lib\site-packages\tensorflow_core\lite\python\tflite_convert.py", line 221, in _convert_tf2_model
    tflite_model = converter.convert()
  File "C:\Users\test\anaconda3\envs\tf2\lib\site-packages\tensorflow_core\lite\python\lite.py", line 400, in convert
    raise ValueError("This converter can only convert a single "
ValueError: This converter can only convert a single ConcreteFunction. Converting multiple functions is under development.

The command entered is following:

> tflite_convert --graph_def_file=tflite_graph.pb --output_file=detect.tflite --input_shapes=1,300,300,3 --input_arrays=normalized_input_image_tensor --output_arrays=TFLite_Detection_PostProcess --allow_custom_ops --saved_model_dir=<path to model directory>\object_detection\tflite\

Windows 10
Tensorflow 2.0.0
Python 3.7.9

**Comment by lu-wang-g** [comment]
@MeghnaNatraj Can you please take a look at this?

**Comment by MeghnaNatraj** [comment]
@soumyaiitkgp Update your command as follows:

`tflite_convert --graph_def_file=tflite_graph.pb --output_file=detect.tflite --input_shapes=1,300,300,3 --input_arrays=normalized_input_image_tensor --output_arrays=TFLite_Detection_PostProcess --allow_custom_ops`

You don't have to provide a saved model when you're already providing a graph def.

**Comment by lu-wang-g** [comment]
Closing the issue. Feel free to reopen.
