### ISSUE TITLE
TensorBuffer does not support data type: INT32

### ISSUE THREAD

**Issue by gdemos01** [tensorflow/tflite-support#637]
TensorBuffer inputFeature0 = TensorBuffer.createFixedSize(new int[]{1}, DataType.FLOAT32);
    inputFeature0.loadBuffer(byteBuffer);
    TensorBuffer inputFeature1 = TensorBuffer.createFixedSize(new int[]{1}, DataType.FLOAT32);
    inputFeature1.loadBuffer(byteBuffer);
    TensorBuffer inputFeature2 = TensorBuffer.createFixedSize(new int[]{1}, DataType.INT32);
    inputFeature2.loadBuffer(byteBuffer);
    TensorBuffer inputFeature3 = TensorBuffer.createFixedSize(new int[]{1, 26}, DataType.FLOAT32);
    inputFeature3.loadBuffer(byteBuffer);

    // Runs model inference and gets result.
    FinalTestModel.Outputs outputs = model.process(inputFeature0, inputFeature1, inputFeature2, inputFeature3);
    TensorBuffer outputFeature0 = outputs.getOutputFeature0AsTensorBuffer();
    TensorBuffer outputFeature1 = outputs.getOutputFeature1AsTensorBuffer();

    // Releases model resources if no longer used.
    model.close();

**Error**
`
java.lang.AssertionError: TensorBuffer does not support data type: INT32
        at org.tensorflow.lite.support.tensorbuffer.TensorBuffer.createFixedSize(TensorBuffer.java:79)
        at com.example.scdemo.MainActivity.onCreate(MainActivity.java:61)
        at android.app.Activity.performCreate(Activity.java:8198)
        at android.app.Activity.performCreate(Activity.java:8182)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3765)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3968)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8512)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
`

Input feature 2 seems to be causing, a problem since it is an INT32. Is there a workaround this issue?

**Comment by lu-wang-g** [comment]
`TensorBuffer` only supports `FLOAT32` and `UINT8` so far. So for `inputFeature2` you cannot use `TensorBuffer`, but need to create a `ByteBuffer` or an array on your own.

**Comment by gdemos01** [comment]
> `TensorBuffer` only supports `FLOAT32` �and `UINT8` so far. So for `inputFeature2` you cannot use `TensorBuffer`, but need to create a `ByteBuffer` or an array on your own.

Yes but model.process() only accepts TensorBuffers as input. How can I use the model with byte buffers instead?

**Comment by gdemos01** [comment]
> > `TensorBuffer` only supports `FLOAT32` �and `UINT8` so far. So for `inputFeature2` you cannot use `TensorBuffer`, but need to create a `ByteBuffer` or an array on your own.
> 
> Yes but model.process() only accepts TensorBuffers as input. How can I use the model with byte buffers instead?

I solved the issue by using the TF Lite Interpreter instead. Still, I was wondering if there is a hack of doing it using the "tensorflow.lite.support" instead.

**Comment by lu-wang-g** [comment]
Unfortunately, it won't be possible to use the support library for `inputFeature2`.  When using `Interpreter`, you can hack it a little bit by:

```
Object[] inputs = {inputFeature0.getBuffer(), inputFeature1.getBuffer(), inputFeature2Buffer, inputFeature3.getBuffer()}
Map<Integer, Object> outputs = new HashMap<>();
TensorBuffer outputFeature0 = TensorBuffer.createFixedSize(....);
outputs.put(0, outputFeature0.getBuffer());
Interpreter. runForMultipleInputsOutputs(inputs, outputs);
```

**Comment by lu-wang-g** [comment]
Closing this issue for now. Let me know if you have other questions.
